// Generated by CoffeeScript 1.6.2
(function() {
  var CanvasManager, DragHandle, RangeIndicator, SpectrumDisplay, loadSound, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  CanvasManager = root.CanvasManager;

  DragHandle = root.DragHandle;

  RangeIndicator = root.RangeIndicator;

  SpectrumDisplay = root.SpectrumDisplay;

  loadSound = function(context, url, callback) {
    var request;

    request = new XMLHttpRequest();
    request.open('GET', url, true);
    request.responseType = 'arraybuffer';
    request.onload = function() {
      return context.decodeAudioData(request.response, callback);
    };
    return request.send();
  };

  $(document).ready(function() {
    var bandPassInd, canvas, canvasManager, context, handle1, handle2, noiseBuffer, onLoaded, setup, specDisplay, toLoad, voiceBuffer;

    context = new webkitAudioContext();
    voiceBuffer = null;
    noiseBuffer = null;
    canvas = $('canvas');
    canvasManager = new CanvasManager(canvas);
    specDisplay = new SpectrumDisplay(canvasManager, 30, 0, 600, 300);
    handle1 = new DragHandle(canvasManager, 20, 350, 30, 30, "#005500", {
      minX: 15,
      maxX: 615
    });
    handle2 = new DragHandle(canvasManager, 80, 350, 30, 30, "#005500", {
      minX: 15,
      maxX: 615
    });
    bandPassInd = new RangeIndicator(canvasManager, 0, 300, "#005500", handle1, handle2);
    canvasManager.render();
    toLoad = 2;
    onLoaded = function() {
      toLoad--;
      if (toLoad === 0) {
        return setup();
      }
    };
    loadSound(context, 'atlys.mp3', function(buffer) {
      voiceBuffer = buffer;
      return onLoaded();
    });
    loadSound(context, 'noise.mp3', function(buffer) {
      noiseBuffer = buffer;
      return onLoaded();
    });
    return setup = function() {
      var freq, intervalId, pipeline, playing, _i, _len, _ref;

      pipeline = new AudioPipeline(context, noiseBuffer);
      specDisplay.analyser = pipeline.postAnalyser;
      pipeline.setInterference(1500, 1, [900, 1100, 1300, 1500, 1700, 1900]);
      pipeline.bandPass.set(2, 8, 1500, 1);
      handle1.onMove = handle2.onMove = function() {
        var Q, delta, f1, f2, freq, x1, x2, _ref;

        x1 = handle1.getMarkerX();
        x2 = handle2.getMarkerX();
        if (x1 > x2) {
          _ref = [x2, x1], x1 = _ref[0], x2 = _ref[1];
        }
        f1 = specDisplay.convertXtoF(x1, context.sampleRate);
        f2 = specDisplay.convertXtoF(x2, context.sampleRate);
        delta = f2 - f1;
        freq = (f1 + f2) / 2;
        Q = freq / delta;
        pipeline.bandPass.setFrequency(freq);
        return pipeline.bandPass.setQ(Q);
      };
      _ref = [900, 1100, 1300, 1500, 1700, 1900];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        freq = _ref[_i];
        pipeline.toneFilter.addFrequency(freq);
      }
      playing = false;
      intervalId = null;
      return $('#play-button').click(function() {
        if (playing) {
          playing = false;
          pipeline.stop();
          return clearInterval(intervalId);
        } else {
          playing = true;
          pipeline.play(voiceBuffer);
          return intervalId = setInterval(function() {
            return canvasManager.render();
          }, 30);
        }
      });
    };
  });

}).call(this);
